# Generated by Django 4.0.4 on 2022-09-12 12:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
