# Generated by Django 4.0.4 on 2022-09-12 13:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_alter_story_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
