# Generated by Django 3.1.7 on 2022-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='poster',
            field=models.ImageField(default='', upload_to='posters'),
            preserve_default=False,
        ),
    ]
