# Generated by Django 3.1.7 on 2022-04-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_story_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created']},
        ),
    ]
