# Generated by Django 3.1.7 on 2022-04-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
